<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Gemmi.Core\Gemmi.Core.csproj" />
    <ProjectReference Include="..\Gemmi.Hardware\Gemmi.Hardware.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Speech" Version="10.0.10" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
