<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Gemmi.Core\Gemmi.Core.csproj" />
    <ProjectReference Include="..\Gemmi.Hardware\Gemmi.Hardware.csproj" />
    <ProjectReference Include="..\Gemmi.Perception\Gemmi.Perception.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <StartupObject>Gemmi.Scratch.Step5OhShinyEvaluatorTest</StartupObject>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
